# Generated by Django 6.0 on 2025-12-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livecareapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirm_password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password2',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
