# Generated by Django 6.0 on 2025-12-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livecareapp', '0003_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
