# Generated by Django 6.0 on 2025-12-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livecareapp', '0004_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
